feature: attesters and badges api
sismo-core/sismo-data-sources pull request #32
Opened 2022-07-16 12:50 UTC by Kakktuss

2022-07-17 07:22 UTC, nicolas-geniteau requested changes

2022-07-17 07:22 UTC, nicolas-geniteau commented on src/topics/attester/attester.ts
>  import { AttestationsCollection } from "../attestations-collection/attestations-collection";
`import { AttestationsCollection } from "../attestations-collection/attestations-collection";`
->
`import { AttestationsCollection } from "../attestations-collection";`

2022-07-17 07:22 UTC, nicolas-geniteau commented on src/topics/badge/badge.ts
>    name?: string;
name should not be mandatory ?

Below, in Badge constructor, `requirements` and `collectionId` are not used

2022-07-18 07:04 UTC, leosayous21 commented on src/topics/badge/badge.ts
> +        name: this.name ?? "",
Name / description / Image should be mendatory

2022-07-18 07:04 UTC, leosayous21 commented on attesters/index.ts
> +import * as fs from "node:fs/promises";
Yes, let's do it with a networks field for every network where it is deployed

2022-07-18 12:45 UTC, nicolas-geniteau requested changes

2022-07-18 12:45 UTC, nicolas-geniteau commented on attesters/hydra-s1-simple/index.ts
> +    configurations: {
rename `configurations` to `networkConfiguration` ?
Or have something like:
```
configuration: {
  network: {}
}
```
@leosayous21

2022-07-18 12:45 UTC, nicolas-geniteau commented on attesters/hydra-s1-simple/index.ts
>  import { AttestationsCollection } from "../../src/topics/attestations-collection/attestations-collection";
`import { AttestationsCollection } from "../../src/topics/attestations-collection";`

2022-07-18 12:45 UTC, nicolas-geniteau commented on src/topics/attester/attester.test.ts
> +  describe("getConstructNetworkAttester", () => {
duplicated ??

2022-07-18 12:45 UTC, nicolas-geniteau commented on src/topics/attester/attester.test.ts
> +jest.mock("../../../attesters/hydra-s1-simple", () => {
You should not use any mock here. I will show you an example with  group-generators (in another PR)

2022-07-18 12:45 UTC, nicolas-geniteau commented on src/topics/badge/badge.api.ts
> +      await getConstructNetworkAttester(network as AttesterNetwork, attester)
return 404 if not found ?

2022-07-18 12:45 UTC, nicolas-geniteau commented on src/topics/badge/badge.api.ts
> +      attester[1].attestationsCollections.map((collection) => collection?.badge)
why `collection?.badge` and not `collection.badge` ?

2022-07-25 07:25 UTC, closed without merging